package packet.mateo.bd;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class BDSQLiteHelper extends SQLiteOpenHelper {

    private static int version = 11;
    private static String nombreDB = "MateoBD";
    private static SQLiteDatabase.CursorFactory factory = null;

    public BDSQLiteHelper(Context context) {
        super(context, nombreDB, factory, version);
    }


    @Override
    public void onCreate(SQLiteDatabase db) {

        db.execSQL(sqlCreacionChampion);
        db.execSQL(sqlinsertChampions);
        db.execSQL(sqlinsertChampions2);
        db.execSQL(sqlinsertChampions3);
        db.execSQL(sqlinsertChampions5);
        db.execSQL(sqlCreacionTablaNotificaciones);


    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        if (newVersion > oldVersion) {
            db.execSQL("DROP TABLE IF EXISTS notificaciones");
            // db.execSQL("DROP TABLE IF EXISTS users");
            db.execSQL("DROP TABLE IF EXISTS champion");

            //creacion

            db.execSQL(sqlCreacionChampion);
            db.execSQL(sqlinsertChampions);
            db.execSQL(sqlinsertChampions2);
            db.execSQL(sqlinsertChampions3);
            db.execSQL(sqlinsertChampions5);

            db.execSQL(sqlCreacionTablaNotificaciones);

        }
    }


    private String sqlCreacionTablaNotificaciones = "CREATE TABLE notificaciones(" +
            "_id INTEGER PRIMARY KEY," +
            "titulo TEXT," +
            "contenido TEXT," +
            "tipo INTEGER," +
            "leido INTEGER)";


    private String sqlCreacionChampion = "CREATE TABLE IF NOT EXISTS champion (\n" +
            // "    _id INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
            "    type TEXT,\n" +
            "    format TEXT,\n" +
            "    version TEXT,\n" +
            "    data_key TEXT,\n" +
            "    data_properties_version TEXT,\n" +
            "    _id TEXT PRIMARY KEY ,\n" +
            "    data_properties_key INT,\n" +
            "    data_properties_name TEXT,\n" +
            "    data_properties_title TEXT,\n" +
            "    data_properties_blurb TEXT,\n" +
            "    data_properties_info_attack INT,\n" +
            "    data_properties_info_defense INT,\n" +
            "    data_properties_info_magic INT,\n" +
            "    data_properties_info_difficulty INT,\n" +
            "    data_properties_image_full TEXT,\n" +
            "    data_properties_image_sprite TEXT,\n" +
            "    data_properties_image_group TEXT,\n" +
            "    data_properties_image_x INT,\n" +
            "    data_properties_image_y INT,\n" +
            "    data_properties_image_w INT,\n" +
            "    data_properties_image_h INT,\n" +
            "    data_properties_tags TEXT,\n" +
            "    data_properties_partype TEXT,\n" +
            "    data_properties_stats_hp NUMERIC(5, 2),\n" +
            "    data_properties_stats_hpperlevel NUMERIC(5, 2),\n" +
            "    data_properties_stats_mp NUMERIC(5, 2),\n" +
            "    data_properties_stats_mpperlevel NUMERIC(3, 1),\n" +
            "    data_properties_stats_movespeed NUMERIC(4, 1),\n" +
            "    data_properties_stats_armor NUMERIC(5, 3),\n" +
            "    data_properties_stats_armorperlevel NUMERIC(3, 2),\n" +
            "    data_properties_stats_spellblock NUMERIC(3, 1),\n" +
            "    data_properties_stats_spellblockperlevel NUMERIC(3, 2),\n" +
            "    data_properties_stats_attackrange NUMERIC(4, 1),\n" +
            "    data_properties_stats_hpregen NUMERIC(5, 3),\n" +
            "    data_properties_stats_hpregenperlevel NUMERIC(3, 2),\n" +
            "    data_properties_stats_mpregen NUMERIC(5, 3),\n" +
            "    data_properties_stats_mpregenperlevel NUMERIC(4, 3),\n" +
            "    data_properties_stats_crit NUMERIC(2, 1),\n" +
            "    data_properties_stats_critperlevel NUMERIC(2, 1),\n" +
            "    data_properties_stats_attackdamage NUMERIC(6, 4),\n" +
            "    data_properties_stats_attackdamageperlevel NUMERIC(6, 5),\n" +
            "    data_properties_stats_attackspeedoffset NUMERIC(6, 5),\n" +
            "    data_properties_stats_attackspeedperlevel NUMERIC(4, 3)\n" +
            ");\n";

    private String sqlinsertChampions = "INSERT INTO champion VALUES\n" +
            "    ('champion','standAloneComplex','6.24.1','Aatrox','6.24.1','Aatrox',266,'Aatrox','the Darkin Blade','Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox''s ...',8,4,3,4,'Aatrox.png','champion0.png','champion',0,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Ahri','6.24.1','Ahri',103,'Ahri','the Nine-Tailed Fox','Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',3,4,8,5,'Ahri.png','champion0.png','champion',48,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Akali','6.24.1','Akali',84,'Akali','the Fist of Shadow','There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',5,3,8,7,'Akali.png','champion0.png','champion',96,0,48,48,'Assassin','Energy',587.8,85.0,200.0,0.0,350.0,26.38,3.5,32.1,1.25,125.0,8.34,0.65,50.0,0.0,0.0,0.0,58.376,3.2,-0.1,3.1),\n" +
            "    ('champion','standAloneComplex','6.24.1','Alistar','6.24.1','Alistar',12,'Alistar','the Minotaur','As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran''s many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...',6,9,5,7,'Alistar.png','champion0.png','champion',144,0,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Amumu','6.24.1','Amumu',32,'Amumu','the Sad Mummy','''''Solitude can be lonelier than death.''''<br><br>A lonely and melancholy soul from ancient Shurima, Amumu roams the world in search of a friend. Cursed by an ancient spell, he is doomed to remain alone forever, as his touch is death and his affection ...',2,6,8,3,'Amumu.png','champion0.png','champion',192,0,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Anivia','6.24.1','Anivia',34,'Anivia','the Cryophoenix','Anivia is a being of the coldest winter, a mystical embodiment of ice magic, and an ancient protector of the Freljord. She commands all the power and fury of the land itself, calling the snow and bitter wind to defend her home from those who would ...',1,4,10,10,'Anivia.png','champion0.png','champion',240,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Annie','6.24.1','Annie',1,'Annie','the Dark Child','There have always been those within Noxus who did not agree with the evils perpetrated by the Noxian High Command. The High Command had just put down a coup attempt from the self-proclaimed Crown Prince Raschallion, and a crackdown on any form of ...',2,3,10,6,'Annie.png','champion0.png','champion',288,0,48,48,'Mage','MP',511.68,76.0,334.0,50.0,335.0,19.22,4.0,30.0,0.0,575.0,5.42,0.55,6.0,0.8,0.0,0.0,50.41,2.625,0.08,1.36),\n" +
            " ('champion','standAloneComplex','11.4.1','Aphelios','11.4.1','Aphelios',523,'Aphelios','the Weapon of the Faithful','Emerging from moonlight''s shadow with weapons drawn, Aphelios kills the enemies of his faith in brooding silence—speaking only through the certainty of his aim, and the firing of each gun. Though fueled by a poison that renders him mute, he is guided by...',6,2,1,10,'Aphelios.png','champion0.png','champion',336,0,48,48,'Marksman','Mana',530,88,348,42,325,28,3,26,0.5,550,3.25,0.55,6.5,0.4,0,0,57,2.4,2.1,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Ashe','6.24.1','Ashe',22,'Ashe','the Frost Archer','With each arrow she fires from her ancient ice-enchanted bow, Ashe proves she is a master archer. She chooses each target carefully, waits for the right moment, and then strikes with power and precision. It is with this same vision and focus that she ...',7,3,2,4,'Ashe.png','champion0.png','champion',336,0,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','AurelionSol','6.24.1','AurelionSol',136,'Aurelion Sol','The Star Forger','Aurelion Sol once graced the vast emptiness of the cosmos with celestial wonders of his own devising. Now, he is forced to wield his awesome power at the behest of a space-faring empire that tricked him into servitude. Desiring a return to his ...',2,3,8,7,'AurelionSol.png','champion0.png','champion',384,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +

            "    ('champion','standAloneComplex','6.24.1','Azir','6.24.1','Azir',268,'Azir','the Emperor of the Sands','''''Shurima was once the glory of Runeterra. I will make it so again.''''<br><br>Azir was a mortal emperor of Shurima in a far distant age, a proud man who stood at the cusp of immortality. His hubris saw him betrayed and murdered at the moment of his ...',6,3,8,9,'Azir.png','champion0.png','champion',432,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Bard','6.24.1','Bard',432,'Bard','the Wandering Caretaker','Bard travels through realms beyond the imagination of mortal beings. Some of Valoran''s greatest scholars have spent their lives trying to understand the mysteries he embodies. This enigmatic spirit has been given many names throughout the history of ...',4,4,5,9,'Bard.png','champion0.png','champion',0,48,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Blitzcrank','6.24.1','Blitzcrank',53,'Blitzcrank','the Great Steam Golem','Zaun is a place where both magic and science have gone awry, and the unchecked nature of experimentation has taken its toll. However, Zaun''s lenient restrictions allow their researchers and inventors the leeway to push the bounds of science at an ...',4,8,5,4,'Blitzcrank.png','champion0.png','champion',48,48,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Brand','6.24.1','Brand',63,'Brand','the Burning Vengeance','In a faraway place known as Lokfar there was a seafaring marauder called Kegan Rodhe. As was his people''s way, Kegan sailed far and wide with his fellows, stealing treasures from those unlucky enough to catch their attention. To some, he was a ...',2,2,9,4,'Brand.png','champion0.png','champion',96,48,48,48,'Mage','MP',507.68,76.0,375.6,42.0,340.0,21.88,3.5,30.0,0.0,550.0,5.42,0.55,8.005,0.6,0.0,0.0,57.04,3.0,0.0,1.36),\n" +
            "    ('champion','standAloneComplex','6.24.1','Braum','6.24.1','Braum',201,'Braum','the Heart of the Freljord','''''Would you like a bedtime story?''''<br><br>''''Grandma, I''m too old for that.''''<br><br>''''You''re never too old to be told a story.''''<br><br>The girl reluctantly crawls into bed and waits, knowing she won''t win this battle. A bitter wind howls outside, ...',3,9,4,3,'Braum.png','champion0.png','champion',144,48,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Caitlyn','6.24.1','Caitlyn',51,'Caitlyn','the Sheriff of Piltover','''''Go ahead, run. I''ll give you a five minute head start.''''<br><br>One of the reasons Piltover is known as the City of Progress is because it has an extraordinarily low crime rate. This hasn''t always been the case; brigands and thieves of all sorts ...',8,2,2,6,'Caitlyn.png','champion0.png','champion',192,48,48,48,'Marksman','MP',524.4,80.0,313.7,35.0,325.0,22.88,3.5,30.0,0.0,650.0,5.67,0.55,7.4,0.55,0.0,0.0,53.66,2.18,0.1,4.0),\n" +
            "    ('champion','standAloneComplex','6.24.1','Camille','6.24.1','Camille',164,'Camille','the Steel Shadow','Weaponized to execute outside the boundaries of the law, Camille Ferros is an elegant and elite operative who ensures the commerce of the Piltover machine with its Zaunite underbelly runs smoothly. Raised among manners and money, she is the Principal ...',8,6,3,4,'Camille.png','champion4.png','champion',144,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Cassiopeia','6.24.1','Cassiopeia',69,'Cassiopeia','the Serpent''s Embrace','Cassiopeia is a terrifying creature - half woman, half snake - whose slightest glance brings death. The youngest daughter of one of Noxus'' most influential families, she was once a beautiful and cunning temptress capable of manipulating the hardest ...',2,3,9,10,'Cassiopeia.png','champion0.png','champion',240,48,48,48,'Mage','MP',525.0,75.0,375.0,60.0,328.0,25.0,3.5,30.0,0.0,550.0,5.5,0.5,6.0,0.8,0.0,0.0,53.0,3.0,-0.034,1.5),\n" +
            "    ('champion','standAloneComplex','6.24.1','Chogath','6.24.1','Chogath',31,'Cho''Gath','the Terror of the Void','There is a place between dimensions, between worlds. To some it is known as the Outside, to others it is the Unknown. To those that truly know, however, it is called the Void. Despite its name, the Void is not an empty place, but rather the home of ...',3,7,7,5,'Chogath.png','champion0.png','champion',288,48,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Corki','6.24.1','Corki',42,'Corki','the Daring Bombardier','When Heimerdinger and his yordle colleagues migrated to Piltover, they embraced science as a way of life, and they immediately made several groundbreaking contributions to the techmaturgical community. What yordles lack in stature, they make up for ...',8,3,6,6,'Corki.png','champion0.png','champion',336,48,48,48,'Marksman','MP',512.76,82.0,350.16,34.0,325.0,23.38,3.5,30.0,0.0,550.0,5.42,0.55,7.42,0.55,0.0,0.0,56.0,3.5,0.0,2.3),\n" +
            "    ('champion','standAloneComplex','6.24.1','Darius','6.24.1','Darius',122,'Darius','the Hand of Noxus','There is no greater symbol of Noxian might than Darius, the nation''s most feared and battle-hardened warrior. Orphaned at a young age, Darius had to fight to keep himself and his younger brother alive. By the time he joined the military, he had ...',9,5,1,2,'Darius.png','champion0.png','champion',384,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Diana','6.24.1','Diana',131,'Diana','Scorn of the Moon','''''I am the light coursing in the soul of the moon.''''<br><br>Bearing her crescent moonblade, Diana fights as a warrior of the Lunari, a faith all but quashed in the lands around Mount Targon. Clad in shimmering armor the color of winter snow at night, ...',7,6,8,4,'Diana.png','champion0.png','champion',432,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Draven','6.24.1','Draven',119,'Draven','the Glorious Executioner','Unlike his brother Darius, victory in battle was never enough for Draven. He craved recognition, acclaim, and glory. He first sought greatness in the Noxian military, but his flair for the dramatic went severely underappreciated. Thirsting for a ...',9,3,1,8,'Draven.png','champion0.png','champion',0,96,48,48,'Marksman','MP',557.76,82.0,360.56,39.0,330.0,25.544,3.3,30.0,0.0,550.0,6.175,0.7,8.04,0.65,0.0,0.0,55.8,2.91,-0.08,2.7),\n" +
            "    ('champion','standAloneComplex','6.24.1','DrMundo','6.24.1','DrMundo',36,'Dr. Mundo','the Madman of Zaun','''''Beware the Madman of Zaun. In his eyes, you are already dead''''<br><br>It is said that the man now known as Dr. Mundo was born without any sort of conscience. Instead, he had an unquenchable desire to inflict pain through experimentation. By the time ...',5,7,6,5,'DrMundo.png','champion0.png','champion',48,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Ekko','6.24.1','Ekko',245,'Ekko','the Boy Who Shattered Time','A prodigy from the rough streets of Zaun, Ekko manipulates time to spin any situation to his advantage. Using his own invention, the Zero-Drive, he explores the branching possibilities of reality. As well as experimenting with multi-dimensional ...',5,3,7,8,'Ekko.png','champion0.png','champion',96,96,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Elise','6.24.1','Elise',60,'Elise','the Spider Queen','''''Beauty is power too, and can strike swifter than any sword.''''<br><br>Elise is a deadly predator who dwells in a shuttered, lightless palace, deep in the Immortal Bastion of Noxus. Once she was mortal, the mistress of a once-powerful house, but the ...',6,5,7,9,'Elise.png','champion0.png','champion',144,96,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Evelynn','6.24.1','Evelynn',28,'Evelynn','the Widowmaker','Swift and lethal, Evelynn is one of the most deadly - and expensive - assassins in all of Runeterra. Able to merge with the shadows at will, she patiently stalks her prey, waiting for the right moment to strike. While Evelynn is clearly not entirely ...',4,2,7,10,'Evelynn.png','champion0.png','champion',192,96,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Ezreal','6.24.1','Ezreal',81,'Ezreal','the Prodigal Explorer','The intrepid young adventurer Ezreal has explored some of the most remote and abandoned locations on Runeterra. During an expedition to the buried ruins of ancient Shurima, he recovered an amulet of incredible mystical power. Likely constructed to be ...',7,2,6,7,'Ezreal.png','champion0.png','champion',240,96,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','FiddleSticks','6.24.1','FiddleSticks',9,'Fiddlesticks','the Harbinger of Doom','For nearly twenty years, Fiddlesticks has stood alone in the easternmost summoning chamber of the Institute of War. Only the burning emerald light of his unearthly gaze pierces the musty darkness of his dust-covered home. It is here that the Harbinger ...',2,3,9,9,'FiddleSticks.png','champion0.png','champion',288,96,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Fiora','6.24.1','Fiora',114,'Fiora','the Grand Duelist','''''I have come to kill you for the sake of honor. And though you possess none, still you die.''''<br>The most feared duelist in all Valoran, Fiora is as renowned for her brusque manner and cunning mind as she is for the speed of her bluesteel rapier. ...',10,4,2,3,'Fiora.png','champion0.png','champion',336,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Fizz','6.24.1','Fizz',105,'Fizz','the Tidal Trickster','Centuries ago, an ancient water-dwelling race built a hidden city beneath a mountain in the sea. Though these creatures had their enemies, the city was an impenetrable fortress, and, in the safety it provided, they grew complacent. Fizz, however, ...',6,4,7,6,'Fizz.png','champion0.png','champion',384,96,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Galio','6.24.1','Galio',3,'Galio','the Sentinel''s Sorrow','''''There is no such thing as redemption. Only penance.''''<br><br>Long before the regulation of magic, mages experimented with the creation of artificial life. Now forbidden, instilling golems with reason was once not so uncommon a practice amongst the ...',3,7,6,3,'Galio.png','champion0.png','champion',432,96,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Gangplank','6.24.1','Gangplank',41,'Gangplank','the Saltwater Scourge','''''I was cutting throats and sinking Noxian war galleys when you were still pissing your britches, boy. You don''t want to take me on.''''<br><br>As unpredictable as he is brutal, the dethroned reaver king known as Gangplank is feared far and wide. Where ...',7,6,4,9,'Gangplank.png','champion1.png','champion',0,0,48,48,'Fighter','MP',540.0,82.0,282.0,40.0,345.0,26.0,3.0,32.1,1.25,125.0,6.0,0.6,7.5,0.7,0.0,0.0,56.0,3.0,0.0,3.2),\n" +
            "    ('champion','standAloneComplex','6.24.1','Garen','6.24.1','Garen',86,'Garen','The Might of Demacia','Throughout Valoran, the resolve of Demacia''s military is alternately celebrated or despised, but always respected. Their ''''zero tolerance'''' moral code is strictly upheld by civilians and soldiers alike. In combat, this means Demacian troops may not ...',7,7,1,5,'Garen.png','champion1.png','champion',48,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Gnar','6.24.1','Gnar',150,'Gnar','the Missing Link','The jungle does not forgive blindness. Every broken branch tells a story.<br><br>I''ve hunted every creature this jungle has to offer. I was certain there were no challenges left here, but now there is something new. Each track is the size of a ...',6,5,5,8,'Gnar.png','champion1.png','champion',96,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Gragas','6.24.1','Gragas',79,'Gragas','the Rabble Rouser','The only thing more important to Gragas than fighting is drinking. His unquenchable thirst for stronger ale has led him in search of the most potent and unconventional ingredients to toss in his still. Impulsive and unpredictable, this rowdy carouser ...',4,7,6,5,'Gragas.png','champion1.png','champion',144,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Graves','6.24.1','Graves',104,'Graves','the Outlaw','Malcolm Graves is a wanted man in every realm, city and empire he has visited. Tough, strong-willed, and above all, relentless, through his life of crime he has amassed (then invariably lost) a small fortune.',8,5,3,3,'Graves.png','champion1.png','champion',192,0,48,48,'Marksman','MP',551.12,84.0,322.2,40.0,340.0,24.376,3.4,30.0,0.0,425.0,6.675,0.7,7.9,0.7,0.0,0.0,60.83,2.41,0.3,2.6),\n" +
            "    ('champion','standAloneComplex','6.24.1','Hecarim','6.24.1','Hecarim',120,'Hecarim','the Shadow of War','''''Break their ranks and ride them down without mercy. Crush the living and feast on their terror.''''<br><br>Hecarim is an armored colossus who charges from the Shadow Isles at the head of a deathly host of spectral horsemen to hunt the living. A ...',8,6,4,6,'Hecarim.png','champion1.png','champion',240,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Heimerdinger','6.24.1','Heimerdinger',74,'Heimerdinger','the Revered Inventor','From the Journal of Professor Cecil B. Heimerdinger<br><br>10.14<br><br>09:15<br><br>Current meteorological conditions in Bandle City seem optimal. Atmospheric pressure is ideal for today''s experiments!<br><br>Running a fifth trial for my ...',2,6,8,8,'Heimerdinger.png','champion1.png','champion',288,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);";
    private String sqlinsertChampions2 = "INSERT INTO champion VALUES\n" +
            "    ('champion','standAloneComplex','6.24.1','Illaoi','6.24.1','Illaoi',420,'Illaoi','the Kraken Priestess','''''I''m not big on sermons. Broken bones teach better lessons.''''<br>Illaoi''s powerful physique is dwarfed only by her indomitable faith. As the prophet of the Great Kraken, she uses a huge, golden idol to rip her foes'' spirits from their bodies and ...',8,6,3,4,'Illaoi.png','champion1.png','champion',336,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Irelia','6.24.1','Irelia',39,'Irelia','the Will of the Blades','''''The sword flourishes, as though painting with blood.''''<br><br>The Ionians have developed some of the most breathtaking and deadly martial arts in all of Runeterra - just one manifestation of their pursuit of enlightenment. The most remarkable blade ...',7,4,5,5,'Irelia.png','champion1.png','champion',384,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Ivern','6.24.1','Ivern',427,'Ivern','the Green Father','Ivern Bramblefoot, known to many as the Green Father, is a peculiar half man, half tree who roams Runeterra''s forests, cultivating life everywhere he goes. He knows the secrets of the natural world, and holds deep friendships with all things that grow,...',3,5,7,7,'Ivern.png','champion4.png','champion',96,48,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Janna','6.24.1','Janna',40,'Janna','the Storm''s Fury','There are those sorcerers who give themselves over to the primal powers of nature, forgoing the learned practice of magic. Such a sorceress is Janna, who first learned magic as an orphan growing up amidst the chaos that is the city-state of Zaun. ...',3,5,7,7,'Janna.png','champion1.png','champion',432,0,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','JarvanIV','6.24.1','JarvanIV',59,'Jarvan IV','the Exemplar of Demacia','''''There is only one truth, and you will find it at the point of my lance.''''<br><br>As the royal family of Demacia for centuries, members of the Lightshield line have spent their lives waging war against any who opposed Demacian ethics. It is said that ...',6,8,3,5,'JarvanIV.png','champion1.png','champion',0,48,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Jax','6.24.1','Jax',24,'Jax','Grandmaster at Arms','It is seldom the case where a champion is defined by his actions after joining the League of Legends rather than before. Such is the case with Jax, for whom the argument could be made that he is the most prolific tournament fighter currently at the ...',7,5,7,5,'Jax.png','champion1.png','champion',48,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Jayce','6.24.1','Jayce',126,'Jayce','the Defender of Tomorrow','Armed with wit, charm, and his signature transforming hammer, Jayce lives to protect his native Piltover. Long before his nation called him a hero, however, he was a promising young inventor. When Piltover commissioned him to study a rare arcane ...',8,4,3,7,'Jayce.png','champion1.png','champion',96,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Jhin','6.24.1','Jhin',202,'Jhin','the Virtuoso','''''Art requires a certain...cruelty.''''<br><br>Jhin is a meticulous criminal psychopath who believes murder is art. Once an Ionian prisoner, but freed by shadowy elements within Ionia''s ruling council, the serial killer now works as their cabal''s ...',10,2,6,6,'Jhin.png','champion1.png','champion',144,48,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Jinx','6.24.1','Jinx',222,'Jinx','the Loose Cannon','Jinx lives to wreak havoc without a thought for the consequences, leaving a trail of mayhem and panic in her wake. A manic and impulsive criminal, she despises nothing more than boredom, and gleefully brings her own volatile brand of pandemonium to ...',9,2,4,6,'Jinx.png','champion1.png','champion',192,48,48,48,'Marksman','MP',517.76,82.0,245.6,45.0,325.0,22.88,3.5,30.0,0.0,525.0,5.84,0.5,6.68,1.0,0.0,0.0,58.46,2.41,0.0,1.0),\n" +
            "   ('champion','standAloneComplex','11.4.1','Kaisa','11.4.1','Kaisa',145,'Kai''Sa','Daughter of the Void','Claimed by the Void when she was only a child, Kai''Sa managed to survive through sheer tenacity and strength of will. Her experiences have made her a deadly hunter and, to some, the harbinger of a future they would rather not live to see. Having entered...',8,5,3,6,'Kaisa.png','champion1.png','champion',384,48,48,48,'Marksman','Mana',600,88,344.88,38,335,28,3,30,0.5,525,3.5,0.55,8.2,0.45,0,0,59,2,1.8,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Kalista','6.24.1','Kalista',429,'Kalista','the Spear of Vengeance','''''When wronged, we seek justice. When hurt, we strike back. When betrayed, the Spear of Vengeance strikes!''''<br><br>A specter of wrath and retribution, Kalista is the undying spirit of vengeance, an armored nightmare summoned from the Shadow Isles to ...',8,2,4,7,'Kalista.png','champion1.png','champion',240,48,48,48,'Marksman','MP',517.76,83.0,231.8,35.0,325.0,19.012,3.5,30.0,0.0,550.0,6.0,0.55,6.3,0.4,0.0,0.0,63.0,2.9,-0.03,2.5),\n" +
            "    ('champion','standAloneComplex','6.24.1','Karma','6.24.1','Karma',43,'Karma','the Enlightened One','Karma is a woman of indomitable will and unbound spiritual power. She is the soul of Ionia made manifest and an inspiring presence on the battlefield, shielding her allies and turning back her foes. A strong leader torn between tradition and ...',1,7,8,5,'Karma.png','champion1.png','champion',288,48,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Karthus','6.24.1','Karthus',30,'Karthus','the Deathsinger','''''Death is not the end of the journey, it is just the beginning...''''<br><br>The harbinger of oblivion, Karthus is an undying spirit whose haunting songs are a prelude to the horror of his nightmarish appearance. The living fear the eternity of undeath,...',2,2,10,7,'Karthus.png','champion1.png','champion',336,48,48,48,'Mage','MP',516.0,75.0,372.48,61.0,335.0,20.88,3.5,30.0,0.0,450.0,6.42,0.55,6.0,0.8,0.0,0.0,45.66,3.25,0.0,2.11),\n" +
            "    ('champion','standAloneComplex','6.24.1','Kassadin','6.24.1','Kassadin',38,'Kassadin','the Void Walker','There is a place between dimensions and between worlds. To some it is known as the Outside, to others it is the Unknown. To most, however, it is called the Void. Despite its name, the Void is not an empty place, but rather the home of unspeakable ...',3,5,8,8,'Kassadin.png','champion1.png','champion',384,48,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Katarina','6.24.1','Katarina',55,'Katarina','the Sinister Blade','Driven by an intense killer instinct, Katarina uses her talents as an assassin for the glory of Noxus, and the continued elevation of her family. While her fervor drives her to ever-greater feats, it can sometimes lead her astray.<br><br>From ...',4,3,9,8,'Katarina.png','champion1.png','champion',432,48,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Kayle','6.24.1','Kayle',10,'Kayle','The Judicator','In a world far away where an ancient war still rages, Kayle was a great hero - the strongest of an immortal race committed to destroying evil wherever it could be found. For ten thousand years, Kayle fought tirelessly for her people, wielding her ...',6,6,7,7,'Kayle.png','champion1.png','champion',0,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            " ('champion','standAloneComplex','11.4.1','Kayn','11.4.1','Kayn',141,'Kayn','the Shadow Reaper','A peerless practitioner of lethal shadow magic, Shieda Kayn battles to achieve his true destiny—to one day lead the Order of Shadow into a new era of Ionian supremacy. He wields the sentient darkin weapon Rhaast, undeterred by its creeping corruption of...',10,6,1,8,'Kayn.png','champion1.png','champion',240,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Kennen','6.24.1','Kennen',85,'Kennen','the Heart of the Tempest','There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',6,4,7,4,'Kennen.png','champion1.png','champion',48,96,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Khazix','6.24.1','Khazix',121,'Kha''Zix','the Voidreaver','A vicious Void predator, Kha''Zix infiltrated Valoran to devour the land''s most promising creatures. With each kill he absorbs his prey''s strength, evolving to grow more powerful. Kha''Zix hungers most to conquer and consume Rengar, the one beast he ...',9,4,3,6,'Khazix.png','champion1.png','champion',96,96,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Kindred','6.24.1','Kindred',203,'Kindred','The Eternal Hunters','''''Tell me again, little Lamb, which things are ours to take?''''<br>''''All things, Dear Wolf.''''<br>Separate, but never parted, Kindred represents the twin essences of death. Lamb''s arrow offers a swift release for those who accept their fate. Wolf hunts ...',8,2,2,4,'Kindred.png','champion1.png','champion',144,96,48,48,'Marksman','MP',540.0,85.0,300.0,35.0,325.0,20.0,3.5,30.0,0.0,500.0,7.0,0.55,6.97,0.4,0.0,0.0,54.0,1.7,0.0,2.5),\n" +
            "    ('champion','standAloneComplex','6.24.1','Kled','6.24.1','Kled',240,'Kled','the Cantankerous Cavalier','''''A sane man would run . . . but I ain''t the runnin'' kind!''''<br><br>A warrior as fearless as he is ornery, Kled is a popular folk hero in Noxus. Embodying the furious bravado of his nation, he is an icon beloved by the empire''s soldiers, distrusted by ...',8,2,2,7,'Kled.png','champion4.png','champion',48,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','KogMaw','6.24.1','KogMaw',96,'Kog''Maw','the Mouth of the Abyss','''''If that''s just hungry, I don''t want to see angry.''''<br><br>When the prophet Malzahar was reborn in Icathia, he was led there by an ominous voice which thereafter anchored itself to his psyche. From within, this voice bestowed upon him terrible ...',8,2,5,6,'KogMaw.png','champion1.png','champion',192,96,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Leblanc','6.24.1','Leblanc',7,'LeBlanc','the Deceiver','Every city has its dark side, even one whose reputation is already of a questionable hue. Noxus - though its name is already invoked with a mixture of reverence and revulsion - is no exception to this simple truth. Deep within the winding dungeons ...',1,4,10,9,'Leblanc.png','champion1.png','champion',240,96,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','LeeSin','6.24.1','LeeSin',64,'Lee Sin','the Blind Monk','As a young teen, Lee Sin was intent on becoming a summoner. His will and dedication were unmatched by any of his peers, and his skill drew the attention of Reginald Ashram, the League''s High Councilor at the time. While studying at the Arcanum Majoris,...',8,5,3,6,'LeeSin.png','champion1.png','champion',288,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Leona','6.24.1','Leona',89,'Leona','the Radiant Dawn','''''If you would shine like a sun, first you must burn like one.''''<br><br>Imbued with the fire of the sun, Leona is a warrior templar of the Solari who defends Mount Targon with her Zenith Blade and Shield of Daybreak. Her skin shimmers with starfire ...',4,8,3,4,'Leona.png','champion1.png','champion',336,96,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','11.4.1','Lillia','11.4.1','Lillia',876,'Lillia','the Bashful Bloom','Intensely shy, the fae fawn Lillia skittishly wanders Ionia''s forests. Hiding just out of sight of mortals—whose mysterious natures have long captivated, but intimidated, her—Lillia hopes to discover why their dreams no longer reach the ancient Dreaming...',0,2,10,8,'Lillia.png','champion2.png','champion',192,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Lissandra','6.24.1','Lissandra',127,'Lissandra','the Ice Witch','Lissandra''s magic twists the pure power of ice into something dark and terrible. With the force of her black ice, she does more than freeze - she impales and crushes those who oppose her. To the terrified denizens of the north, she is known only as ...',2,5,8,6,'Lissandra.png','champion1.png','champion',384,96,48,48,'Mage','MP',506.12,75.0,304.0,50.0,325.0,20.216,3.7,30.0,0.0,550.0,6.92,0.55,5.67,0.4,0.0,0.0,50.536,2.7,0.0,1.36),\n" +
            "    ('champion','standAloneComplex','6.24.1','Lucian','6.24.1','Lucian',236,'Lucian','the Purifier','Lucian wields relic weapons imbued with ancient power and stands a stalwart guardian against the undead. His cold conviction never wavers, even in the face of the maddening horrors he destroys beneath his hail of purifying fire. Lucian walks alone on ...',8,5,3,6,'Lucian.png','champion1.png','champion',432,96,48,48,'Marksman','MP',554.4,80.0,348.88,38.0,335.0,24.04,3.0,30.0,0.0,500.0,6.19,0.65,8.175,0.7,0.0,0.0,57.46,2.41,-0.02,3.3),\n" +
            "    ('champion','standAloneComplex','6.24.1','Lulu','6.24.1','Lulu',117,'Lulu','the Fae Sorceress','Perhaps more than any other champion in the League, Lulu marches to the beat of her own drum. During her youth in Bandle City, she spent most of her time wandering alone in the forest or lost in a daydream. It wasn''t that she was antisocial; the ...',4,5,7,5,'Lulu.png','champion2.png','champion',0,0,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Lux','6.24.1','Lux',99,'Lux','the Lady of Luminosity','Born to the prestigious Crownguards, the paragon family of Demacian service, Luxanna was destined for greatness. She grew up as the family''s only daughter, and she immediately took to the advanced education and lavish parties required of families as ...',2,4,9,5,'Lux.png','champion2.png','champion',48,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Malphite','6.24.1','Malphite',54,'Malphite','Shard of the Monolith','There is a world of perfect harmony, where all are part of the whole. The Monolith is the essence of all creation, and its denizens are but singular pieces of it. It is beautiful in its symmetry, and in its almost complete lack of uncertainty. The ...',5,9,7,2,'Malphite.png','champion2.png','champion',96,0,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Malzahar','6.24.1','Malzahar',90,'Malzahar','the Prophet of the Void','Many men have gone mad beneath the glare of the Shurima sun, but it was during the night''s chilling embrace that Malzahar relinquished his sanity. Malzahar was born a seer, blessed with the gift of prophecy. His talent, though unrefined, promised to ...',2,2,9,6,'Malzahar.png','champion2.png','champion',144,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Maokai','6.24.1','Maokai',57,'Maokai','the Twisted Treant','''''All around me are empty husks, soulless and unafraid... but I will bring them fear.''''<br><br>Maokai is a rageful, towering treant who fights the unnatural horrors of the Shadow Isles. He was twisted into a force of vengeance after a magical ...',3,8,6,3,'Maokai.png','champion2.png','champion',192,0,48,48,'Mage','MP',572.2,90.0,377.28,43.0,335.0,28.72,4.0,32.1,1.25,125.0,7.0,0.75,7.205,0.45,0.0,0.0,63.544,3.3,-0.1,2.125);";
    private String sqlinsertChampions3 = "INSERT INTO champion VALUES\n" +
            "    ('champion','standAloneComplex','6.24.1','MasterYi','6.24.1','MasterYi',11,'Master Yi','the Wuju Bladesman','Through the ancient martial art of Wuju, Master Yi has tempered his body and sharpened his mind until thought and action have become one. Though he chooses to enter into violence as a last resort, the grace and speed with which he wields his blade ...',10,4,2,4,'MasterYi.png','champion2.png','champion',240,0,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','MissFortune','6.24.1','MissFortune',21,'Miss Fortune','the Bounty Hunter','''''The bigger the risk, the bigger the bounty.''''<br><br>Beauty and danger: There are few who can match Miss Fortune in either. One of Bilgewater''s most infamous bounty hunters, she built her legend upon a swathe of bullet-riddled corpses and captured ...',8,2,5,1,'MissFortune.png','champion2.png','champion',288,0,48,48,'Marksman','MP',530.0,85.0,325.84,35.0,325.0,24.04,3.0,30.0,0.0,550.0,6.19,0.65,8.04,0.65,0.0,0.0,46.0,1.0,-0.04734,3.0),\n" +
            "    ('champion','standAloneComplex','6.24.1','MonkeyKing','6.24.1','MonkeyKing',62,'Wukong','the Monkey King','During the chaos of the Rune Wars, an enormous runestone was lost deep within the Plague Jungles. It remained there, untouched for centuries, emanating a potent magic which infused nearby wildlife with sentience and vitality. A group of monkeys who ...',8,5,2,3,'MonkeyKing.png','champion2.png','champion',336,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Mordekaiser','6.24.1','Mordekaiser',82,'Mordekaiser','the Iron Revenant','''''All things must die... and yet I live on.''''<br><br>The baleful revenant Mordekaiser is among the most terrifying and hateful spirits haunting the Shadow Isles. He has existed for countless centuries, shielded from true death by necromantic sorcery ...',4,6,7,4,'Mordekaiser.png','champion2.png','champion',384,0,48,48,'Fighter','None',525.0,73.0,0.0,0.0,325.0,20.0,3.75,32.1,1.25,175.0,4.0,0.3,0.0,0.0,0.0,0.0,61.0,5.0,0.04,2.2),\n" +
            "    ('champion','standAloneComplex','6.24.1','Morgana','6.24.1','Morgana',25,'Morgana','Fallen Angel','There is a world far away populated by graceful and beautiful winged beings gifted with immortality, where an ancient conflict still rages. Like so many conflicts, this war split families. One side proclaimed themselves as beings of perfect order and ...',1,6,8,1,'Morgana.png','champion2.png','champion',432,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Nami','6.24.1','Nami',267,'Nami','the Tidecaller','Nami channels the primal energies of the ocean, harnessing its mystical restorative properties and commanding the raw power of the tides themselves. Though many doubted her, Nami had the bravery and determination to take on a dangerous quest when no ...',4,3,7,5,'Nami.png','champion2.png','champion',0,48,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Nasus','6.24.1','Nasus',75,'Nasus','the Curator of the Sands','''''What was fallen will be great again.''''<br><br>Nasus is an imposing, jackal-headed Ascended being from ancient Shurima, a heroic figure regarded as a demigod by the people of the desert. Fiercely intelligent, he was a guardian of knowledge and ...',7,5,6,6,'Nasus.png','champion2.png','champion',48,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Nautilus','6.24.1','Nautilus',111,'Nautilus','the Titan of the Depths','Once, Nautilus was a sailor commissioned by the Institute of War to explore the uncharted reaches of the Guardian''s Sea. This expedition took him deep into unknown waters where he and his crew found a vast section of black oozing liquid that none of ...',4,6,6,6,'Nautilus.png','champion2.png','champion',96,48,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "  ('champion','standAloneComplex','11.4.1','Neeko','11.4.1','Neeko',518,'Neeko','the Curious Chameleon','Hailing from a long lost tribe of vastaya, Neeko can blend into any crowd by borrowing the appearances of others, even absorbing something of their emotional state to tell friend from foe in an instant. No one is ever sure where—or who—Neeko might be...',1,1,9,5,'Neeko.png','champion2.png','champion',0,96,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Nidalee','6.24.1','Nidalee',76,'Nidalee','the Bestial Huntress','There are few dwellers, let alone champions, residing in the blasted and dangerous lands that lie south of the Great Barrier. Much of that world still bears the scars of past Runes Wars, especially the mysterious Kumungu Jungle. There are ...',5,4,7,8,'Nidalee.png','champion2.png','champion',144,48,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Nocturne','6.24.1','Nocturne',56,'Nocturne','the Eternal Nightmare','Before Nocturne, people believed that dreams were figments of their imagination, meaningless images that flashed through the mind when one slept. This belief was put to the test when a rash of sleep-related incidents started afflicting summoners of ...',9,5,2,4,'Nocturne.png','champion2.png','champion',192,48,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Nunu','6.24.1','Nunu',20,'Nunu','the Yeti Rider','Sometimes bonds of friendship become stronger than even bonds of blood. When those bonds link a fearless boy to a fearsome Yeti, the bond becomes a force to be reckoned with. Given the responsibility of taming a terrifying beast, Nunu forged a ...',4,6,7,4,'Nunu.png','champion2.png','champion',240,48,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Olaf','6.24.1','Olaf',2,'Olaf','the Berserker','Most men would say that death is a thing to be feared; none of those men would be Olaf. The Berserker lives only for the roar of a battle cry and the clash of steel. Spurred on by his hunger for glory and the looming curse of a forgettable death, Olaf ...',9,5,3,3,'Olaf.png','champion2.png','champion',288,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Orianna','6.24.1','Orianna',61,'Orianna','the Lady of Clockwork','There once was a Piltovian man named Corin Reveck who had a daughter named Orianna, whom he loved more than anything else in the world. Though Orianna had incredible talent for dancing, she was deeply fascinated by the champions of the League of ...',4,3,9,7,'Orianna.png','champion2.png','champion',336,48,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            " ('champion','standAloneComplex','11.4.1','Ornn','11.4.1','Ornn',516,'Ornn','The Fire below the Mountain','Ornn is the Freljordian spirit of forging and craftsmanship. He works in the solitude of a massive smithy, hammered out from the lava caverns beneath the volcano Hearth-Home. There he stokes bubbling cauldrons of molten rock to purify ores and fashion...',5,9,3,5,'Ornn.png','champion2.png','champion',288,96,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Pantheon','6.24.1','Pantheon',80,'Pantheon','the Artisan of War','''''Bring forth one true champion, or a hundred more like you, and then we shall have a battle that will be spoken of until the end of time.''''<br><br>The peerless warrior known as Pantheon is a nigh-unstoppable paragon of battle. He was born among the ...',9,4,3,4,'Pantheon.png','champion2.png','champion',384,48,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Poppy','6.24.1','Poppy',78,'Poppy','Keeper of the Hammer','''''I''m no hero. Just a yordle with a hammer.''''<br><br>Runeterra has no shortage of valiant champions, but few are as tenacious as Poppy. Bearing a hammer twice the length of her body, this determined yordle has spent untold years searching for the ...',6,7,2,6,'Poppy.png','champion2.png','champion',432,48,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','11.4.1','Pyke','11.4.1','Pyke',555,'Pyke','the Bloodharbor Ripper','A renowned harpooner from the slaughter docks of Bilgewater, Pyke should have met his death in the belly of a gigantic jaull-fish… and yet, he returned. Now, stalking the dank alleys and backways of his former hometown, he uses his new supernatural...',9,3,1,7,'Pyke.png','champion2.png','champion',432,96,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Quinn','6.24.1','Quinn',133,'Quinn','Demacia''s Wings','Quinn and Valor are an elite ranger team. With crossbow and claw, they undertake their nation''s most dangerous missions deep within enemy territory, from swift reconnaissance to lethal strikes. The pair''s unbreakable bond is deadly on the battlefield, ...',9,4,2,5,'Quinn.png','champion2.png','champion',0,96,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "  ('champion','standAloneComplex','11.4.1','Qiyana','11.4.1','Qiyana',246,'Qiyana','Empress of the Elements','In the jungle city of Ixaocan, Qiyana plots her own ruthless path to the high seat of the Yun Tal. Last in line to succeed her parents, she faces those who stand in her way with brash confidence and unprecedented mastery over elemental magic. With the...',0,2,4,8,'Qiyana.png','champion3.png','champion',0,0,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "     ('champion','standAloneComplex','11.4.1','Rakan','11.4.1','Rakan',497,'Rakan','The Charmer','As mercurial as he is charming, Rakan is an infamous vastayan troublemaker and the greatest battle-dancer in Lhotlan tribal history. To the humans of the Ionian highlands, his name has long been synonymous with wild festivals, uncontrollable parties...',2,4,8,5,'Rakan.png','champion3.png','champion',96,0,48,48,'Support','Mana',540,85,315,50,335,32,3.9,32,1.25,300,5,0.5,8.75,0.5,0,0,62,3.5,3,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Rammus','6.24.1','Rammus',33,'Rammus','the Armordillo','''''OK.''''<br><br>Idolized by many, dismissed by some, mystifying to all, the curious being, Rammus, is an enigma. Protected by a spiked shell, Rammus inspires increasingly disparate theories on his origin wherever he goes - from demigod, to sacred ...',4,10,5,5,'Rammus.png','champion2.png','champion',48,96,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','RekSai','6.24.1','RekSai',421,'Rek''Sai','the Void Burrower','The largest and fiercest of her species, Rek''Sai is a merciless predator that tunnels through the earth to ambush and devour her prey. Her insatiable hunger has laid waste to entire regions of the once-great Shuriman empire. Merchants, traders and ...',8,5,2,3,'RekSai.png','champion2.png','champion',96,96,48,48,'Fighter','Battlefury',570.0,90.0,100.0,0.0,335.0,24.0,3.4,32.1,1.25,175.0,7.34,0.65,0.0,0.0,0.0,0.0,55.628,3.35,0.0,2.0),\n" +
            "    ('champion','standAloneComplex','11.4.1','Rell','11.4.1','Rell',526,'Rell','the Iron Maiden','The product of brutal experimentation at the hands of the Black Rose, Rell is a defiant, living weapon determined to topple Noxus. Her childhood was one of misery and horror, enduring unspeakable procedures to perfect and weaponize her magical control...',0,0,0,0,'Rell.png','champion3.png','champion',240,0,48,48,'Tank','Mana',540,90,350,45,335,35,3,32.1,1.25,175,7,0.55,6,0.35,0,0,55,3,2,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Renekton','6.24.1','Renekton',58,'Renekton','the Butcher of the Sands','''''Blood and vengeance.''''<br><br>Renekton is a terrifying, rage-fueled Ascended being from the scorched deserts of Shurima. Once, he was his empire''s most esteemed warrior, leading the armies of Shurima to countless victories. However, after the ...',8,5,2,3,'Renekton.png','champion2.png','champion',144,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Rengar','6.24.1','Rengar',107,'Rengar','the Pridestalker','On every wall of his den, the trophy hunter Rengar mounts the heads, horns, claws, and fangs of the most lethal creatures in Valoran. Though his collection is extensive, he remains unsatisfied, tirelessly seeking greater game. He takes time with every ...',7,4,2,8,'Rengar.png','champion2.png','champion',192,96,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Riven','6.24.1','Riven',92,'Riven','the Exile','''''There is a place between war and murder in which our demons lurk.''''<br><br>In Noxus, any citizen may rise to power regardless of race, gender, or social standing - strength is all that matters. It was with committed faith in this ideal that Riven ...',8,5,1,8,'Riven.png','champion2.png','champion',240,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Rumble','6.24.1','Rumble',68,'Rumble','the Mechanized Menace','''''Ugh, it''s gonna take forever to scrape your face off my suit!''''<br><br>Even amongst yordles, Rumble was always the runt of the litter. As such, he was used to being bullied. In order to survive, he had to be scrappier and more resourceful than his ...',3,6,8,10,'Rumble.png','champion2.png','champion',288,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Ryze','6.24.1','Ryze',13,'Ryze','the Rune Mage','''''Take care with this world. What is made can be unmade.''''<br><br>Widely considered one of the most adept sorcerers on Runeterra, Ryze is an ancient, hard-bitten archmage with an impossibly heavy burden to bear. Armed with a boundless constitution and ...',2,2,10,7,'Ryze.png','champion2.png','champion',336,96,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +

            "    ('champion','standAloneComplex','11.4.1','Samira','11.4.1','Samira',360,'Samira','the Desert Rose','Samira stares death in the eye with unyielding confidence, seeking thrill wherever she goes. After her Shuriman home was destroyed as a child, Samira found her true calling in Noxus, where she built a reputation as a stylish daredevil taking on...',8,5,3,6,'Samira.png','champion3.png','champion',48,48,48,48,'Marksman','Mana',530,88,348.88,38,335,26,3,30,0.5,500,3.25,0.55,8.18,0.7,0,0,57,2.3,3.3,NULL)," +
            " ('champion','standAloneComplex','11.4.1','Senna','11.4.1','Senna',235,'Senna','the Redeemer','Cursed from childhood to be haunted by the supernatural Black Mist, Senna joined a sacred order known as the Sentinels of Light, and fiercely fought back—only to be killed, her soul imprisoned in a lantern by the cruel wraith Thresh. But refusing to...',7,2,6,7,'Senna.png','champion3.png','champion',144,48,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Sejuani','6.24.1','Sejuani',113,'Sejuani','the Winter''s Wrath','Sejuani was weaned on hardship and reared on barbarity. Where others succumbed to the harshness of the Freljord, she was tempered by it until pain became power, hunger an encouragement, and frost an ally in culling the weak. Through her ordeals, she ...',5,7,6,4,'Sejuani.png','champion2.png','champion',384,96,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','11.4.1','Seraphine','11.4.1','Seraphine',147,'Seraphine','the Starry-Eyed Songstress','Born in Piltover to Zaunite parents, Seraphine can hear the souls of others—the world sings to her, and she sings back. Though these sounds overwhelmed her in her youth, she now draws on them for inspiration, turning the chaos into a symphony. She...',0,0,0,0,'Seraphine.png','champion3.png','champion',192,48,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "   ('champion','standAloneComplex','11.4.1','Sett','11.4.1','Sett',875,'Sett','the Boss','A leader of Ionia''s growing criminal underworld, Sett rose to prominence in the wake of the war with Noxus. Though he began as a humble challenger in the fighting pits of Navori, he quickly gained notoriety for his savage strength, and his ability to...',8,5,1,2,'Sett.png','champion3.png','champion',240,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Shaco','6.24.1','Shaco',35,'Shaco','the Demon Jester','Most would say that death isn''t funny. It isn''t, unless you''re Shaco - then it''s hysterical. He is Valoran''s first fully functioning homicidal comic; he jests until someone dies, and then he laughs. The figure that has come to be known as the Demon ...',8,4,6,9,'Shaco.png','champion2.png','champion',432,96,48,48,'Assassin','MP',582.12,84.0,297.2,40.0,350.0,24.88,3.5,32.1,1.25,125.0,8.37,0.55,7.155,0.45,0.0,0.0,57.58,3.5,-0.1,3.0),\n" +
            "    ('champion','standAloneComplex','6.24.1','Shen','6.24.1','Shen',98,'Shen','the Eye of Twilight','''''The Eye is blind to fear, to hate, to love - to all things that would sway equilibrium.''''<br><br>Leader of a secret clan of mystic warriors, Shen serves as the Eye of Twilight, entrusted to enforce equilibrium in the world. Longing to remain free ...',3,9,3,4,'Shen.png','champion3.png','champion',0,0,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Shyvana','6.24.1','Shyvana',102,'Shyvana','the Half-Dragon','A half-breed born from the union between dragon and human, Shyvana searched all her life for belonging. Persecution forged her into a brutal warrior, and those who dare stand against Shyvana face the fiery beast lurking just beneath her skin....',8,6,3,4,'Shyvana.png','champion3.png','champion',48,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Singed','6.24.1','Singed',27,'Singed','the Mad Chemist','Singed descended from a long line of Zaun''s revered chemists. Even in his youth, his talent for concocting potions far outstripped that of his peers, and he quickly distinguished himself from his less extraordinary chemist compatriots. It came as no ...',4,8,7,5,'Singed.png','champion3.png','champion',96,0,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Sion','6.24.1','Sion',14,'Sion','The Undead Juggernaut','BLOOD.<br><br>SMELL IT.<br><br>WANT. ACHING. NEED!<br><br>CLOSE NOW. THEY COME.<br><br>NO CHAINS? FREE! KILL!<br><br>IN REACH. YES! DIE! DIE!<br><br>Gone. Too quick. No fight. More. I want... more.<br><br>A voice? Unfamiliar. I see him. The Grand ...',5,9,3,5,'Sion.png','champion3.png','champion',144,0,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Sivir','6.24.1','Sivir',15,'Sivir','the Battle Mistress','''''I don''t care what face is on your coin, as long as it pays.''''<br><br>Sivir is a renowned fortune hunter and mercenary captain who plies her trade in the deserts of Shurima. Armed with her legendary jeweled crossblade, she has fought and won ...',9,3,1,4,'Sivir.png','champion3.png','champion',192,0,48,48,'Marksman','MP',515.76,82.0,284.0,50.0,335.0,22.21,3.25,30.0,0.0,500.0,5.17,0.55,8.01,0.9,0.0,0.0,57.46,2.41,0.0,1.6),\n" +
            "    ('champion','standAloneComplex','6.24.1','Skarner','6.24.1','Skarner',72,'Skarner','the Crystal Vanguard','''''We are one. We cannot be shattered.''''<br><br>Skarner is an immense crystalline scorpion from a hidden valley in Shurima. Part of the ancient Brackern race, Skarner and his kin are known for their great wisdom and deep connection to the land, as ...',7,6,5,5,'Skarner.png','champion3.png','champion',240,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Sona','6.24.1','Sona',37,'Sona','Maven of the Strings','Sona has no memories of her true parents. As an infant, she was found abandoned on the doorstep of an Ionian adoption house, nestled atop an ancient instrument in an exquisite case of unknown origins. She was an unusually well-behaved child, always ...',5,2,8,4,'Sona.png','champion3.png','champion',288,0,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Soraka','6.24.1','Soraka',16,'Soraka','the Starchild','A healer gifted with the magic of the stars, Soraka holds all living creatures close to her heart. She was once a celestial being, but she sacrificed her immortality and entered the world of mortals. So long as evil threatens life in Valoran, Soraka ...',2,5,7,3,'Soraka.png','champion3.png','champion',336,0,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);";

    private String sqlinsertChampions5 = "INSERT INTO champion VALUES\n" +
            "    ('champion','standAloneComplex','6.24.1','Swain','6.24.1','Swain',50,'Swain','the Master Tactician','The earliest account of Swain''s existence comes from a Noxian infirmary doctor''s notes. According to them, Swain limped into the ward without cry or complaint; his right leg was snapped in half, with bone protruding from the skin. A small, scowling ...',2,6,9,8,'Swain.png','champion3.png','champion',384,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Syndra','6.24.1','Syndra',134,'Syndra','the Dark Sovereign','Born with immense magical potential, Syndra loves nothing more than exercising the incredible power at her command. With each passing day, her mastery of magical force grows more potent and devastating. Refusing any notion of balance or restraint, ...',2,3,9,8,'Syndra.png','champion3.png','champion',432,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            " ('champion','standAloneComplex','11.4.1','Sylas','11.4.1','Sylas',517,'Sylas','the Unshackled','Raised in one of Demacia''s lesser quarters, Sylas of Dregbourne has come to symbolize the darker side of the Great City. As a boy, his ability to root out hidden sorcery caught the attention of the notorious mageseekers, who eventually imprisoned him...',3,4,8,5,'Sylas.png','champion3.png','champion',288,96,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','TahmKench','6.24.1','TahmKench',223,'Tahm Kench','the River King','''''The whole world''s a river, and I''m its king.''''<br>Tahm Kench travels Runeterra''s waterways, feeding his insatiable appetite with the misery of the unsuspecting. The singularly charming gourmand savors every moment of his victims'' suffering.  A deal ...',3,9,6,5,'TahmKench.png','champion3.png','champion',0,48,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Taliyah','6.24.1','Taliyah',163,'Taliyah','the Stoneweaver','Taliyah is a nomadic mage from Shurima who weaves stone with energetic enthusiasm and raw determination. Torn between teenage wonder and adult responsibility, she has crossed nearly all of Valoran on a journey to learn the true nature of her growing ...',1,7,8,5,'Taliyah.png','champion3.png','champion',48,48,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Talon','6.24.1','Talon',91,'Talon','the Blade''s Shadow','''''The three deadliest blademasters in all of Valoran are bound to the house of Du Couteau: my father, myself, and Talon. Challenge us, if you dare.''''<br>-- Katarina Du Couteau<br><br>Talon''s earliest memories are the darkness of Noxus'' underground ...',9,3,1,7,'Talon.png','champion3.png','champion',96,48,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Taric','6.24.1','Taric',44,'Taric','the Shield of Valoran','''''The best weapons are beautiful.''''<br><br>Taric is the Aspect of the Protector, wielding incredible power as Runeterra''s guardian of life, love, and beauty. Shamed by a dereliction of duty and exiled from his homeland Demacia, Taric ascended Mount ...',4,8,5,3,'Taric.png','champion3.png','champion',144,48,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Teemo','6.24.1','Teemo',17,'Teemo','the Swift Scout','Teemo is a legend among his yordle brothers and sisters in Bandle City. As far as yordles are concerned, there is something just slightly off about him. While Teemo enjoys the companionship of other yordles, he also insists on frequent solo missions ...',5,3,7,6,'Teemo.png','champion3.png','champion',192,48,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Thresh','6.24.1','Thresh',412,'Thresh','the Chain Warden','''''The mind is a wondrous thing to tear apart.''''<br><br>Sadistic and cunning, Thresh is a restless spirit who prides himself on tormenting mortals and breaking them with slow, excruciating inventiveness. His victims suffer far beyond the point of death,...',5,6,6,7,'Thresh.png','champion3.png','champion',240,48,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Tristana','6.24.1','Tristana',18,'Tristana','the Yordle Gunner','Greatness comes in all shapes and sizes, as proven by this diminutive, cannon-wielding yordle. In a world fraught with turmoil, Tristana refuses to back down from any challenge. She represents the pinnacle of martial proficiency, unwavering courage, ...',9,3,5,4,'Tristana.png','champion3.png','champion',288,48,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Trundle','6.24.1','Trundle',48,'Trundle','the Troll King','Trundle is a hulking and devious troll with a mischievous streak. There is nothing he can''t beat into submission and bend to his will, not even the ice itself. With his massive, frozen club, he chills his enemies to the core and runs them through with ...',7,6,2,5,'Trundle.png','champion3.png','champion',336,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Tryndamere','6.24.1','Tryndamere',23,'Tryndamere','the Barbarian King','Fueled by his unbridled fury and rage, Tryndamere cuts his way through the tundra, mastering the art of battle by challenging the Freljord''s greatest warriors. The wrathful barbarian seeks revenge on the one who decimated his clan and strikes down all ...',10,5,2,5,'Tryndamere.png','champion3.png','champion',384,48,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','TwistedFate','6.24.1','TwistedFate',4,'Twisted Fate','the Card Master','Twisted Fate is an infamous card sharp and swindler who has gambled and charmed his way across much of the known world, earning the enmity and admiration of the rich and foolish alike. He rarely takes things seriously, greeting each day with a mocking ...',6,2,6,9,'TwistedFate.png','champion3.png','champion',432,48,48,48,'Mage','MP',521.76,82.0,265.84,38.0,330.0,20.542,3.15,30.0,0.0,525.0,5.505,0.6,6.0,0.8,0.0,0.0,49.954,3.3,-0.04,3.22),\n" +
            "    ('champion','standAloneComplex','6.24.1','Twitch','6.24.1','Twitch',29,'Twitch','the Plague Rat','H.I.V.E. Incident Report<br>Code Violation: Industrial Homicide<br>Casefile Status: Unsolved<br>Investigating Agent: Rol, P.<br><br>Team responded to report of suspicious character, criminal activity; proceeded to Sump Works, Sector 90TZ. Sector 90TZ ...',9,2,3,6,'Twitch.png','champion3.png','champion',0,96,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Udyr','6.24.1','Udyr',77,'Udyr','the Spirit Walker','Udyr is more than a man; he is a vessel for the untamed power of four primal animal spirits. When tapping into the spirits'' bestial natures, Udyr can harness their unique strengths: the tiger grants him speed and ferocity, the turtle resilience, the ...',8,7,4,7,'Udyr.png','champion3.png','champion',48,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Urgot','6.24.1','Urgot',6,'Urgot','the Headsman''s Pride','There are warriors who become great for their strength, cunning, or skill with arms. Others simply refuse to die. Urgot, once a great soldier of Noxus, may constitute a case in support of the latter. Prone to diving headlong into enemy battle lines, ...',8,5,3,8,'Urgot.png','champion3.png','champion',96,96,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Varus','6.24.1','Varus',110,'Varus','the Arrow of Retribution','''''The life of an arrow is fleeting, built of nothing but direction and intent.''''<br><br>For his incomparable skill with the bow and his unquestioned sense of honor, Varus was chosen to be the warden of a sacred Ionian temple. The temple was built to ...',7,3,4,2,'Varus.png','champion3.png','champion',144,96,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Vayne','6.24.1','Vayne',67,'Vayne','the Night Hunter','The world is not always as civilized as people might think. There are still those who would follow the blackest paths of magic and become corrupted by the darker powers that flow through Runeterra. Shauna Vayne knows this fact well.<br><br>As a young ...',10,1,1,8,'Vayne.png','champion3.png','champion',192,96,48,48,'Marksman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Veigar','6.24.1','Veigar',45,'Veigar','the Tiny Master of Evil','To most, thoughts of yordles do not conjure images to be feared. The easygoing half-pint race, though fierce, is often regarded with some degree of joviality. Their high-pitched voices and naturally cute forms inspire something of a protective ...',2,2,10,7,'Veigar.png','champion3.png','champion',240,96,48,48,'Mage','MP',492.76,82.0,392.4,52.0,340.0,22.55,3.75,30.0,0.0,525.0,5.42,0.55,6.0,0.8,0.0,0.0,50.71,2.625,0.0,2.24),\n" +
            "    ('champion','standAloneComplex','6.24.1','Velkoz','6.24.1','Velkoz',161,'Vel''Koz','the Eye of the Void','I pass into the sudden glare. Blink. Blink, blink, blink. My eyes adjust and evaluate the landscape before me.<br><br>There''s a scurrying. I look down to find a small, white creature standing on its hind legs, sniffing at my body. It intrigues me....',2,2,10,8,'Velkoz.png','champion3.png','champion',288,96,48,48,'Mage','MP',507.68,76.0,375.6,42.0,340.0,21.88,3.5,30.0,0.0,525.0,5.42,0.55,6.0,0.8,0.0,0.0,54.9379,3.14159,0.0,1.36),\n" +
            "    ('champion','standAloneComplex','11.4.1','Viego','11.4.1','Viego',234,'Viego','The Ruined King','Once ruler of a long-lost kingdom, Viego perished over a thousand years ago when his attempt to bring his wife back from the dead triggered the magical catastrophe known as the Ruination. Transformed into a powerful, unliving wraith tortured by an...',6,4,2,5,'Viego.png','champion4.png','champion',288,48,48,48,'Fighter','None',560,95,10000,0,345,34,4,32,1.25,225,7,0.7,0,0,0,0,57,3.5,2.5,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Vi','6.24.1','Vi',254,'Vi','the Piltover Enforcer','To Vi, every problem is just another brick wall to punch through with her gigantic hextech gauntlets. Though she grew up on the wrong side of the law, Vi now uses her criminal know-how to serve Piltover''s police force. Vi''s brash attitude, abrasive ...',8,5,3,4,'Vi.png','champion3.png','champion',336,96,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Viktor','6.24.1','Viktor',112,'Viktor','the Machine Herald','Early in life, Viktor discovered his passion for science and invention, particularly in the field of mechanical automation. He attended Zaun''s prestigious College of Techmaturgy and led the team that constructed Blitzcrank - a scientific breakthrough ...',2,4,10,9,'Viktor.png','champion3.png','champion',384,96,48,48,'Mage','MP',516.04,78.0,324.0,50.0,335.0,22.72,4.0,30.0,0.0,525.0,7.84,0.65,6.0,0.8,0.0,0.0,52.04,3.0,-0.05,2.11),\n" +
            "    ('champion','standAloneComplex','6.24.1','Vladimir','6.24.1','Vladimir',8,'Vladimir','the Crimson Reaper','There is a temple hidden in the mountains between Noxus and the Tempest Flats, where the secrets of an ancient and terrifying sorcery are kept. The area surrounding the temple is littered with the exsanguinated corpses of those who have mistakenly ...',2,6,8,7,'Vladimir.png','champion3.png','champion',432,96,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Volibear','6.24.1','Volibear',106,'Volibear','the Thunder''s Roar','The unforgiving northern reaches of the Freljord are home to the Ursine, a fierce and warlike race that has endured the barren tundra for thousands of years. Their leader is a furious adversary who commands the force of lightning to strike fear within ...',7,7,4,3,'Volibear.png','champion4.png','champion',0,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Warwick','6.24.1','Warwick',19,'Warwick','the Blood Hunter','Warwick was once a man revered for his ability to track down human specimens for the darkest types of scientific research. When his ambitions exceeded his physical limits, he drank a dangerous elixir to transform himself into an unstoppable manhunter. ...',7,4,4,3,'Warwick.png','champion4.png','champion',48,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','11.4.1','Xayah','11.4.1','Xayah',498,'Xayah','the Rebel','Deadly and precise, Xayah is a vastayan revolutionary waging a personal war to save her people. She uses her speed, guile, and razor-sharp feather blades to cut down anyone who stands in her way. Xayah fights alongside her partner and lover, Rakan, to...',10,6,1,5,'Xayah.png','champion4.png','champion',48,96,48,48,'Marksman','Mana',590,88,340,40,325,25,3,30,0.5,525,3.25,0.75,8.25,0.75,0,0,60,3.5,3.9,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Xerath','6.24.1','Xerath',101,'Xerath','the Magus Ascendant','''''A lifetime as a slave has prepared me for eternity as your master.''''<br><br>Xerath is an Ascended Magus of ancient Shurima, a being of arcane energy writhing in the broken shards of a magical sarcophagus. For millennia, he was trapped beneath the ...',1,3,10,8,'Xerath.png','champion4.png','champion',96,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','XinZhao','6.24.1','XinZhao',5,'Xin Zhao','the Seneschal of Demacia','''''Death is inevitable, one can only avoid defeat.''''<br><br>Whenever Jarvan III, the king of Demacia, delivers one of his rallying speeches from the glinting marble balcony atop the Royal Palace, Xin Zhao is at his side. Coined the Seneschal of Demacia,...',8,6,3,2,'XinZhao.png','champion4.png','champion',144,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Yasuo','6.24.1','Yasuo',157,'Yasuo','the Unforgiven','Yasuo is a man of resolve, an agile swordsman who wields the wind itself to cut down his foes. This once-proud warrior has been disgraced by a false accusation and forced into a desperate fight for survival. With the world turned against him, he will ...',8,4,4,10,'Yasuo.png','champion4.png','champion',192,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "   ('champion','standAloneComplex','11.4.1','Yone','11.4.1','Yone',777,'Yone','the Unforgotten','In life, he was Yone—half-brother of Yasuo, and renowned student of his village''s sword school. But upon his death at the hands of his brother, he found himself hunted by a malevolent entity of the spirit realm, and was forced to slay it with its own...',8,4,4,8,'Yone.png','champion4.png','champion',240,96,48,48,'Fighter','Flow',550,85,500,0,345,28,3.4,32,1.25,175,7.5,0.75,0,0,0,0,60,2,3.5,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Yorick','6.24.1','Yorick',83,'Yorick','Shepherd of Souls','''''These isles… How they scream.''''<br>The last survivor of a long-forgotten religious order, Yorick is both blessed and cursed with power over the dead. Trapped on the Shadow Isles, his only companions are the rotting corpses and shrieking spirits that ...',6,6,4,6,'Yorick.png','champion4.png','champion',240,0,48,48,'Fighter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "  ('champion','standAloneComplex','11.4.1','Yuumi','11.4.1','Yuumi',350,'Yuumi','the Magical Cat','A magical cat from Bandle City, Yuumi was once the familiar of a yordle enchantress, Norra. When her master mysteriously disappeared, Yuumi became the Keeper of Norra''s sentient Book of Thresholds, traveling through portals in its pages to search for...',5,1,8,2,'Yuumi.png','champion4.png','champion',336,96,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Zac','6.24.1','Zac',154,'Zac','the Secret Weapon','Zac is the product of a Zaun experiment to manufacture a hexchem-engineered supersoldier - the Zaun Amorphous Combatant. Combining brute strength with limitless flexibility, he is a versatile juggernaut: a creative fighter who bounces over obstacles ...',3,7,7,8,'Zac.png','champion4.png','champion',288,0,48,48,'Tank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Zed','6.24.1','Zed',238,'Zed','the Master of Shadows','Zed is the first ninja in 200 years to unlock the ancient, forbidden ways. He defied his clan and master, casting off the balance and discipline that had shackled him all his life. Zed now offers power to those who embrace knowledge of the shadows, ...',9,2,1,7,'Zed.png','champion4.png','champion',336,0,48,48,'Assassin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','6.24.1','Ziggs','6.24.1','Ziggs',115,'Ziggs','the Hexplosives Expert','Ziggs was born with a talent for tinkering, but his chaotic, hyperactive nature was unusual among yordle scientists. Aspiring to be a revered inventor like Heimerdinger, he rattled through ambitious projects with manic zeal, emboldened by both his ...',2,4,9,4,'Ziggs.png','champion4.png','champion',384,0,48,48,'Mage','MP',524.4,80.0,384.0,47.0,325.0,21.544,3.3,30.0,0.0,550.0,6.255,0.6,6.0,0.8,0.0,0.0,54.208,3.1,-0.04734,2.0),\n" +
            "    ('champion','standAloneComplex','6.24.1','Zilean','6.24.1','Zilean',26,'Zilean','the Chronokeeper','In the wastelands of Urtistan, there was once a great city. It perished long ago in a terrible Rune War, like most of the lands below the Great Barrier. Nevertheless, one man survived: a sorcerer named Zilean. Being obsessed with time, it was only ...',2,5,8,6,'Zilean.png','champion4.png','champion',432,0,48,48,'Support',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),\n" +
            "    ('champion','standAloneComplex','11.4.1','Zoe','11.4.1','Zoe',142,'Zoe','the Aspect of Twilight','As the embodiment of mischief, imagination, and change, Zoe acts as the cosmic messenger of Targon, heralding major events that reshape worlds. Her mere presence warps the arcane mathematics governing realities, sometimes causing cataclysms without...',1,7,8,5,'Zoe.png','champion5.png','champion',96,0,48,48,'Mage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)," +
            "    ('champion','standAloneComplex','6.24.1','Zyra','6.24.1','Zyra',143,'Zyra','Rise of the Thorns','Longing to take control of her fate, the ancient, dying plant Zyra transferred her consciousness into a human body for a second chance at life. Centuries ago, she and her kind dominated the Kumungu Jungle, using thorns and vines to consume any animal ...',4,3,8,7,'Zyra.png','champion4.png','champion',0,48,48,48,'Support','MP',499.32,74.0,334.0,50.0,340.0,20.04,3.0,30.0,0.0,575.0,5.69,0.5,8.5,0.8,0.0,0.0,53.376,3.2,0.0,2.11);";
}
